/**
 * Executive Dashboard Mock Data
 * Contains stats for all departments and detailed employee metrics.
 */

const executiveData = {
  overall: {
    totalLeads: 12450,
    contactedLeads: 8920,
    closedLeads: 1540,
    closeRate: 0.17, // 17%
    avgCallDuration: "6m 42s",
    totalCalls: 24500,
    avgCallsPerLead: 2.7,
    bestDepartment: "Recruiting",
    bestEmployee: "Mila Petrović",
    leadsByDept: {
      "Recruiting": 5200,
      "Safety": 3100,
      "Fleet": 2100,
      "Accounting": 1500
    },
    closingsByDept: {
      "Recruiting": 850,
      "Safety": 420,
      "Fleet": 180,
      "Accounting": 70
    }
  },
  
  departments: [
    {
      name: "Recruiting",
      employees: 12,
      leads: 5200,
      contacted: 4100,
      closed: 850,
      closeRate: 0.21,
      avgTimeToClose: "5.2 days",
      avgCallDuration: "5m 10s",
      totalCalls: 12500,
      callsPerLead: 3.0,
      followUpRate: 0.45,
      pending: 245
    },
    {
      name: "Safety",
      employees: 8,
      leads: 3100,
      contacted: 2800,
      closed: 420,
      closeRate: 0.15,
      avgTimeToClose: "3.5 days",
      avgCallDuration: "8m 20s",
      totalCalls: 6200,
      callsPerLead: 2.2,
      followUpRate: 0.30,
      pending: 120
    },
    {
      name: "Fleet",
      employees: 6,
      leads: 2100,
      contacted: 1600,
      closed: 180,
      closeRate: 0.11,
      avgTimeToClose: "6.8 days",
      avgCallDuration: "7m 45s",
      totalCalls: 3800,
      callsPerLead: 2.4,
      followUpRate: 0.25,
      pending: 85
    },
    {
      name: "Accounting",
      employees: 4,
      leads: 1500,
      contacted: 1200,
      closed: 70,
      closeRate: 0.06,
      avgTimeToClose: "2.1 days",
      avgCallDuration: "4m 30s",
      totalCalls: 1500,
      callsPerLead: 1.2,
      followUpRate: 0.15,
      pending: 40
    }
  ],

  employees: [
    {
      id: "e1",
      name: "John Doe",
      dept: "Recruiting",
      role: "Senior Recruiter",
      rank: 2,
      score: 94,
      status: "Active",
      leads: 1200,
      contacted: 950,
      closed: 180,
      closeRate: 0.19,
      calls: 3200,
      missedCalls: 45,
      avgCallDuration: "5m 20s",
      longestCall: "24m 10s",
      shortestCall: "0m 45s",
      callsPerLead: 3.4,
      followUpsCompleted: 420,
      followUpsOverdue: 12,
      avgResponseTime: "14 min",
      avgTimeToClose: "5.4 days",
      activeLeads: 85,
      processedLeads: 1115,
      pendingRemoval: 5,
      trend: [65, 78, 82, 94, 88, 94] // last 6 months
    },
    {
      id: "e2",
      name: "Mila Petrović",
      dept: "Recruiting",
      role: "Senior Recruiter",
      rank: 1,
      score: 98,
      status: "Active",
      leads: 1150,
      contacted: 1020,
      closed: 210,
      closeRate: 0.21,
      calls: 3500,
      missedCalls: 20,
      avgCallDuration: "6m 15s",
      longestCall: "32m 05s",
      shortestCall: "1m 10s",
      callsPerLead: 3.4,
      followUpsCompleted: 510,
      followUpsOverdue: 2,
      avgResponseTime: "8 min",
      avgTimeToClose: "4.8 days",
      activeLeads: 60,
      processedLeads: 1090,
      pendingRemoval: 2,
      trend: [80, 85, 90, 92, 96, 98]
    },
    {
      id: "e3",
      name: "Alex Rivera",
      dept: "Recruiting",
      role: "Recruiter",
      rank: 3,
      score: 88,
      status: "Active",
      leads: 1050,
      contacted: 880,
      closed: 145,
      closeRate: 0.16,
      calls: 2800,
      missedCalls: 60,
      avgCallDuration: "4m 50s",
      longestCall: "18m 30s",
      shortestCall: "0m 30s",
      callsPerLead: 3.2,
      followUpsCompleted: 350,
      followUpsOverdue: 25,
      avgResponseTime: "22 min",
      avgTimeToClose: "6.1 days",
      activeLeads: 95,
      processedLeads: 955,
      pendingRemoval: 8,
      trend: [70, 75, 82, 85, 87, 88]
    },
    {
      id: "e4",
      name: "Sara Kim",
      dept: "Recruiting",
      role: "Junior Recruiter",
      rank: 4,
      score: 82,
      status: "Active",
      leads: 900,
      contacted: 720,
      closed: 95,
      closeRate: 0.13,
      calls: 2100,
      missedCalls: 85,
      avgCallDuration: "4m 10s",
      longestCall: "15m 00s",
      shortestCall: "0m 25s",
      callsPerLead: 2.9,
      followUpsCompleted: 210,
      followUpsOverdue: 45,
      avgResponseTime: "35 min",
      avgTimeToClose: "7.2 days",
      activeLeads: 110,
      processedLeads: 790,
      pendingRemoval: 12,
      trend: [60, 65, 70, 78, 80, 82]
    },
    {
      id: "e5",
      name: "Nikola Jovanović",
      dept: "Safety",
      role: "Compliance Manager",
      rank: 1,
      score: 95,
      status: "Active",
      leads: 850,
      contacted: 820,
      closed: 120,
      closeRate: 0.15,
      calls: 1800,
      missedCalls: 10,
      avgCallDuration: "8m 45s",
      longestCall: "45m 00s",
      shortestCall: "2m 30s",
      callsPerLead: 2.2,
      followUpsCompleted: 480,
      followUpsOverdue: 5,
      avgResponseTime: "12 min",
      avgTimeToClose: "3.2 days",
      activeLeads: 30,
      processedLeads: 820,
      pendingRemoval: 3,
      trend: [85, 88, 92, 94, 95, 95]
    },
    {
      id: "e9",
      name: "Dan Richards",
      dept: "Accounting",
      role: "Payroll Admin",
      rank: 1,
      score: 93,
      status: "Active",
      leads: 500,
      contacted: 480,
      closed: 40,
      closeRate: 0.08,
      calls: 700,
      missedCalls: 2,
      avgCallDuration: "4m 10s",
      longestCall: "12m 00s",
      shortestCall: "0m 45s",
      callsPerLead: 1.4,
      followUpsCompleted: 85,
      followUpsOverdue: 0,
      avgResponseTime: "10 min",
      avgTimeToClose: "2.0 days",
      activeLeads: 15,
      processedLeads: 485,
      pendingRemoval: 1,
      trend: [88, 90, 92, 93, 93, 93]
    },
    {
      id: "e10",
      name: "Fred Thompson",
      dept: "Accounting",
      role: "Payroll Clerk",
      rank: 2,
      score: 87,
      status: "Away",
      leads: 450,
      contacted: 400,
      closed: 25,
      closeRate: 0.06,
      calls: 550,
      missedCalls: 12,
      avgCallDuration: "4m 45s",
      longestCall: "14m 30s",
      shortestCall: "1m 00s",
      callsPerLead: 1.4,
      followUpsCompleted: 60,
      followUpsOverdue: 5,
      avgResponseTime: "20 min",
      avgTimeToClose: "2.8 days",
      activeLeads: 25,
      processedLeads: 425,
      pendingRemoval: 2,
      trend: [80, 82, 84, 85, 87, 87]
    }
  ]
};
